### ISSUE TITLE
Feat: chance to target different README files

### ISSUE THREAD

**Issue by fbuireu** [athul/waka-readme#103]
By default (as it should be) it uploads automatically the `README.md` file. I imagine some other scenarios where someone may want to update another file (let's say `README.it.md` beside the activity will be displayed in English).

I'd like the option to use different markdown files to be uploaded using a key like: `TARGET_FILE`.

Thanks for all the work!

**Comment by joe733** [comment]
Hi @fbuireu, I understand your point. The code uses https://github.com/athul/waka-readme/blob/c2075190e1c87c368faf8d7bbb0384864f4832fe/main.py#L356-L374 default `README` provided by the PyGitHub API.

If `TARGET_FILE` can be tweaked, then it could be set for any file, not just `README`. I'm not sure, if we need to move in that direction. Thanks for bringing this up.

cc: @athul
