### ISSUE TITLE
It doesn't seem to work on branches other than the master.

### ISSUE THREAD

**Issue by imhuay** [athul/waka-readme#104]
I'm not asking for this feature, but just add a annotation.

**Comment by joe733** [comment]
Can you please elaborate?

**Comment by EleoXDA** [comment]
he/she probably means that it cannot be run on a specific branch of a readme file (i.e. other than master) - which would require that readme branch file to be merged to master for it to function.

**Comment by imhuay** [comment]
> he/she probably means that it cannot be run on a specific branch of a readme file (i.e. other than master) - which would require that readme branch file to be merged to master for it to function.

Thank you for your explanation.

**Comment by joe733** [comment]
Related #103
