### ISSUE TITLE
Can't distinguish between language

### ISSUE THREAD

**Issue by duktig666** [athul/waka-readme#121]
![image](https://user-images.githubusercontent.com/53132746/231408494-91c9d600-74dd-4538-9931-b3e599b8eb6d.png)

https://github.com/duktig666/duktig666

**Comment by joe733** [comment]
What does your [dashboard](https://wakatime.com/dashboard) show?

![image](https://user-images.githubusercontent.com/38415384/231472360-c91d19bb-be88-4076-b110-cbee15d3d4e0.png)

**Comment by duktig666** [comment]
![image](https://user-images.githubusercontent.com/53132746/231643589-77e31f00-b272-482d-aa2f-5a5be5862d66.png)

**Comment by duktig666** [comment]
This is seven-day data

**Comment by joe733** [comment]
It's `wakatime` labelling languages as `Other` not `waka-readme`.

https://github.com/athul/waka-readme/blob/master/main.py#L301-L316

**Comment by duktig666** [comment]
So how can I avoid this problem?
It should be normal in wakatime's panel
