### ISSUE TITLE
Bug: After Running Steadily in one year, something went wrong

### ISSUE THREAD

**Issue by matchyc** [athul/waka-readme#136]
In github Action:
```
Build container for action use: '/home/runner/work/_actions/athul/waka-readme/master/dockerfile'.
Error: Docker build failed with exit code 1
```

Details:

```
Collecting pyjwt[crypto]>=2.4.0 (from pygithub==1.59.0->-r /app/requirements.txt (line 184))
  ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
      pyjwt[crypto]>=2.4.0 from https://files.pythonhosted.org/packages/2b/4f/e04a8067c7c96c364cef7ef73[90](https://github.com/matchyc/matchyc/actions/runs/5593912022/jobs/10228169051#step:2:90)6504e2f40d690811c021e1a1901473a19/PyJWT-2.8.0-py3-none-any.whl (from pygithub==1.59.0->-r /app/requirements.txt (line 184))
  The command '/bin/sh -c python -m pip install -r /app/requirements.txt' returned a non-zero code: 1
```

**Comment by matchyc** [comment]
It seems a package version is not compatible

**Comment by matchyc** [comment]
> Replace action `athul/waka-readme@master` to `athul/waka-readme@v0.2.1` is optional.

Solved.

**Comment by yunsii** [comment]
It is a temporary workaround, the bug of master branch should still to resolve 😂

**Comment by joe733** [comment]
ref: https://github.com/athul/waka-readme/issues/137#issuecomment-1641338708

**Comment by joe733** [comment]
> Replace action `athul/waka-readme@master` to `athul/waka-readme@v0.2.1` is optional.

Switch back to `master` to receive the patch #138.

**Comment by matchyc** [comment]
> > Replace action `athul/waka-readme@master` to `athul/waka-readme@v0.2.1` is optional.
> 
> Switch back to `athul/waka-readme@master` to receive patch #138.

solved again!
