### ISSUE TITLE
Bug: Failed to build container image

### ISSUE THREAD

**Issue by LiamSho** [athul/waka-readme#137]
Hi, just received an GitHub Actions workflow failed email and it is this job failed.

Failed Action: https://github.com/LiamSho/LiamSho/actions/runs/5594196665

This workflow use `athul/waka-readme@master`. Set it to use `athul/waka-readme@v0.2.1` works well.

It seems like the docker container was failed to build.

I recommend to add a container build test workflow in this project.

**Comment by joe733** [comment]
Tracking upstream https://github.com/pypa/pip/issues/9644

**Comment by AdebayoEmmanuel** [comment]
# From my understanding of the incident, I have put the following together, hope it helps resolve the bug:


# Problem statement:
This morning, I woke up to disturbing news: [AdebayoEmmanuel/AdebayoEmmanuel] Run failed: Waka Readme - main (db943f7) - My [Wakatime Readme action](https://github.com/marketplace/actions/waka-readme) failed!

![run failed email](https://github.com/athul/waka-readme/assets/92952014/17280f94-d2d4-4baa-b463-47d8c0f875e8)


# Troubleshooting done + Findings + Recommendation:

1. Looking through the GitHub action logs, I observed the exact step of the workflow that was failing:

![error log](https://github.com/athul/waka-readme/assets/92952014/45619c67-bec6-471e-9e40-cb28d39abbbb)


2. The error message led me to review line 184 of [athul/waka-readme’s requirements.txt](https://github.com/athul/waka-readme/blob/master/requirements.txt) (I am using athul/waka-readme@v0.2.2 workflow in my yaml. N/B : issue is persistent with both this version and if you use @master). I found out that this is the line that requires [pygithub==1.59.0](https://github.com/PyGithub/PyGithub/tree/main) 

![line 184 trace](https://github.com/athul/waka-readme/assets/92952014/407cbc12-3381-4bd2-ab00-9359ceeb21d0)


3. I checked [PyGithub’s requirements.txt file](https://github.com/PyGithub/PyGithub/blob/main/requirements.txt) and I observed that the requirements were written without pinning their versions using ==. 
![pygithub requirement txt](https://github.com/athul/waka-readme/assets/92952014/74aa978a-b697-4b25-a7e0-8992fe080423)


# Recommendation + RCA:
From the error message on the workflow logs, we understand that while declaring the requirements In --require-hashes mode, all requirements must have their versions pinned with == . Whereas, in [PyGithub’s requirements.txt file](https://github.com/PyGithub/PyGithub/blob/main/requirements.txt), the  requirements were not pinned as required. E.g, pyjwt[crypto]>=2.4.0.

This whole situation resulted to errors that made Docker build to fail with exit code 1 and overall broke the scheduled job.

# Let’s try:
* Waka-readme can should review how pygithub is included into the requirements.txt (decide if it is necessary to require hash - this looks like a security consideration to me and may be important, so if we have to use require hash mode, then we may have to work together with pygithub to apply the fix in recommendation 2)
* PyGithub can update their requirements.txt to hard pin the requirements versions.

**Comment by AdebayoEmmanuel** [comment]
> # From my understanding of the incident, I have put the following together, hope it helps resolve the bug:
> # Problem statement:
> This morning, I woke up to disturbing news: [AdebayoEmmanuel/AdebayoEmmanuel] Run failed: Waka Readme - main (db943f7) - My [Wakatime Readme action](https://github.com/marketplace/actions/waka-readme) failed!
> 
> ![run failed email](https://user-images.githubusercontent.com/92952014/254532213-17280f94-d2d4-4baa-b463-47d8c0f875e8.png)
> 
> # Troubleshooting done + Findings + Recommendation:
> 1. Looking through the GitHub action logs, I observed the exact step of the workflow that was failing:
> 
> ![error log](https://user-images.githubusercontent.com/92952014/254532329-45619c67-bec6-471e-9e40-cb28d39abbbb.png)
> 
> 2. The error message led me to review line 184 of [athul/waka-readme’s requirements.txt](https://github.com/athul/waka-readme/blob/master/requirements.txt) (I am using athul/waka-readme@v0.2.2 workflow in my yaml. N/B : issue is persistent with both this version and if you use @master). I found out that this is the line that requires [pygithub==1.59.0](https://github.com/PyGithub/PyGithub/tree/main)
> 
> ![line 184 trace](https://user-images.githubusercontent.com/92952014/254532410-407cbc12-3381-4bd2-ab00-9359ceeb21d0.png)
> 
> 3. I checked [PyGithub’s requirements.txt file](https://github.com/PyGithub/PyGithub/blob/main/requirements.txt) and I observed that the requirements were written without pinning their versions using ==.
>    ![pygithub requirement txt](https://user-images.githubusercontent.com/92952014/254532423-74aa978a-b697-4b25-a7e0-8992fe080423.png)
> 
> # Recommendation + RCA:
> From the error message on the workflow logs, we understand that while declaring the requirements In --require-hashes mode, all requirements must have their versions pinned with == . Whereas, in [PyGithub’s requirements.txt file](https://github.com/PyGithub/PyGithub/blob/main/requirements.txt), the requirements were not pinned as required. E.g, pyjwt[crypto]>=2.4.0.
> 
> This whole situation resulted to errors that made Docker build to fail with exit code 1 and overall broke the scheduled job.
> 
> # Let’s try:
> * Waka-readme can should review how pygithub is included into the requirements.txt (decide if it is necessary to require hash - this looks like a security consideration to me and may be important, so if we have to use require hash mode, then we may have to work together with pygithub to apply the fix in recommendation 2)
> * PyGithub can update their requirements.txt to hard pin the requirements versions.

@joe733

**Comment by AdebayoEmmanuel** [comment]
Replacing action athul/waka-readme@master to athul/waka-readme@v0.2.1 as recommended here #136 appears to be a working workaround. My workflow ran successfully using @v0.2.1. We can explore the options I recommended above for permanent fix on the master and the latest release @v0.2.2.

**Comment by joe733** [comment]
Hi @AdebayoEmmanuel, thanks for the analysis and recommendation. `PyGithub` as of [`42c3b47`](https://github.com/PyGithub/PyGithub/tree/42c3b47c851c70f5916e503462813fd7c0a0ceba) does not use `pyproject.toml` for dependency specification, we do. We then generate `requirements.txt` just for CI. Speaking of which @LiamSho, I'll add container build test workflow, asap.

In any case `PyGithub` has nothing to do with the container build failure. It is `pip`, which is at fault here. Refer: https://github.com/pypa/pip/issues/9644#issue-813456623

---

**Workarounds**:

1. I could generate `requirements.txt`  without hashes, but then compromise on [secure install](https://pip.pypa.io/en/stable/topics/secure-installs/#secure-installs).
2. Or use [`--no-deps` ](https://pip.pypa.io/en/stable/cli/pip_download/#cmdoption-no-deps), but that won't work in this scenario.
3. `pip` now is capable of reading from `pyproject.toml` directly. But `pip install .` won't accept `--require-hashes`, which then is equivalent of option 1.

---

I'll be working on option 3, along container build tests. Feel free to comment your suggestions below.

**Comment by joe733** [comment]
> This workflow use `athul/waka-readme@master`. Set it to use `athul/waka-readme@v0.2.1` works well.

Switch back to `master` to receive the patch.

**Comment by AdebayoEmmanuel** [comment]
> 
@joe733 
Thank you for clarifying the root cause of the incident and for your time and attention to this bug. I can now clearly see that the real origin of the issue is actually from `Pip` and not `Pygithub`. 

- I understand you have been able to resolve the issue now by using `pyproject.toml` directly without depending on `requirements.txt`. Good work @joe733 - I was not able to follow up immediately on this thread, but I saw and am impressed by the good work you put in to resolve this.
- I am interested in learning how secure install is now being achieved without `--require-hashes`. You mentioned earlier that `pip install` won't accept `--require-hashes` making it equivalent to using `requirements.txt` without secure installs.
- Your commit drew my attention to the contribution guide. I will clone the repo and would be much interested in working together on any future issues as it appears there are no currently open issues to work on at this time. If there is any other way I can contribute, please let me know.

# Good job waka-time, your tool is by far my favorite accountability partner. ❤️

**Comment by AdebayoEmmanuel** [comment]
Switching back. Thanks for the update.

**Comment by joe733** [comment]
> - I am interested in learning how secure install is now being achieved without --require-hashes. You mentioned earlier that pip install won't accept --require-hashes making it equivalent to using requirements.txt without secure installs.

It's `pip install .` not just `pip install` that errors on passing `--require-hashes`:

```console
$ pip install --require-hashes .
Processing /home/us-er/project
ERROR: Can't verify hashes for these file:// requirements because they point to directories:
    file:///home/us-er/project
```

You can read the documentation here: https://pip.pypa.io/en/stable/topics/secure-installs/#secure-installs.

**Comment by AdebayoEmmanuel** [comment]
Oh! Right, thanks for pointing that out.
