### ISSUE TITLE
Display bug with long "languages" names

### ISSUE THREAD

**Issue by guilyx** [athul/waka-readme#15]
Hey !

**Display :**
```
Week: 12 July, 2020 - 19 July, 2020

Go          4 hrs 41 mins       ███████████████████░░░░░░   76.65 % 
Bash        1 hr 9 mins         ████░░░░░░░░░░░░░░░░░░░░░   18.83 % 
Markdown    14 mins             █░░░░░░░░░░░░░░░░░░░░░░░░   03.83 % 
Protocol Buffer1 min               ░░░░░░░░░░░░░░░░░░░░░░░░░   00.52 % 
JSON        0 secs              ░░░░░░░░░░░░░░░░░░░░░░░░░   00.12 %
```

**Description :** 

The progress bars don't have equal lengths, and long names for tools used seems to create some issues as well. I haven't looked into your python code yet so I don't have any PR in mind, I just wanted to open this quick issue to report it.

**Comment by athul** [comment]
Oh, haven't thought that this would cause a problem. I'm sorry for this bug. I'll bring up with a fix for this

**Comment by athul** [comment]
Oh, haven't thought that this would cause a problem. I'm sorry for this bug. I'll bring up with a fix for this

**Comment by athul** [comment]
I have a crude and unpolished way but I don't think this will be the better option since my option would be just to change this line

```diff
-            f"{l['name']}{' '*(12-ln)}{l['text']}{' '*(20-ln_text)}{make_graph(l['percent'])}   {fmt_percent} %")+
+            f"{l['name']}{' '*(16-ln)}{l['text']}{' '*(20-ln_text)}{make_graph(l['percent'])}   {fmt_percent} %")
```

This is more of a hacky solution but in a long term it might clutter the readme if the user has only used languages with names less than 10. I'm open to suggestion and would be happy to get any feedback possible.

cc: @joe733

**Comment by guilyx** [comment]
LGTM as a temporary hack
There's only so much names that could end up breaking it right? Each time it's reported you could add it to a enum class mapping the shortened versions of those long names.

i.e. Protocol Buffer should be Protobuf 

Would require the community to make it grow

**Comment by nelson6e65** [comment]
> 
> 
> LGTM as a temporary hack
> There's only so much names that could end up breaking it right? Each time it's reported you could add it to a enum class mapping the shortened versions of those long names.
> 
> i.e. Protocol Buffer should be Protobuf
> 
> Would require the community to make it grow

Maybe use the file extension instead of long name.

**Comment by athul** [comment]
The languages are received from Wakatime's API and we use it directly. Hardcoding the language extensions are a bit tedious and might lead to discrepancy if the language isn't in the extensions list.
