### ISSUE TITLE
unable to fetch data

### ISSUE THREAD

**Issue by ohitstom** [athul/waka-readme#150]
![image](https://github.com/athul/waka-readme/assets/22730962/eaba819d-5399-4940-bfb5-5d4145f6f069)

**Comment by yozachar** [comment]
Hi @ohitstom, please refer: https://github.com/athul/waka-readme/issues/100#issuecomment-1252185663

**Comment by ohitstom** [comment]
> Hi @ohitstom, please refer: [#100 (comment)](https://github.com/athul/waka-readme/issues/100#issuecomment-1252185663)

thanks for the response, this run has failed with 10 hours+ inbetween and these comments dont really explain much outside of potential ddossing or "i changed the time it runs and now it works" which i cant seem to recreate. my profile also isnt new, but doesnt seem to load when i open it at [wakatime.com/ohitstom](https://wakatime.com/ohitstom)

**Comment by yozachar** [comment]
![image](https://github.com/athul/waka-readme/assets/38415384/95a88854-0c6d-4104-b2ad-f988d3ef6b83)

This is what `athul/waka-readme` sees on HTTP 202. Current solutions has been to wait it out. Let WakaTime server get ready (HTTP 200 OK) with the `all_time` coding data. If you find anything other workarounds feel free to comment.

**Comment by navirobayo** [comment]
Hello. I have been having the same issue it failed Nov 18 and I have been trying to play around with it. I'm able to fetch data from the last 7 days, not all_time as it was before. So.. is this just matter of waiting? 
Here is the [workflows history](https://github.com/navirobayo/navirobayo/actions/workflows/waka-readme.yml) if you want to check it. I appreciate if you can clarify this, I checked the previous duplicated issues but is not clear to me what do I need  to do (I assume is just to wait) @yozachar @ohitstom

**Comment by nuth-vireak** [comment]
Me and my friend also have the same problem
![image](https://github.com/athul/waka-readme/assets/66857698/adf0c0ce-14ad-4c4b-808b-ab2f498443f0)
