### ISSUE TITLE
Unable to fetch data, please rerun workflow since Wed, 15, November 2023

### ISSUE THREAD

**Issue by nuth-vireak** [athul/waka-readme#151]
![image](https://github.com/athul/waka-readme/assets/66857698/936f09a4-4567-4e03-8a59-098048ef16df)

**Comment by navirobayo** [comment]
Same problem here. https://github.com/athul/waka-readme/issues/150#issuecomment-1819521252

**Comment by chaudharydeepanshu** [comment]
I faced the same problem, but it appears to be resolved now.

![image](https://github.com/athul/waka-readme/assets/85361211/266e6e1e-69b3-4fc8-b6ab-ceaab66e3166)

**Comment by navirobayo** [comment]
> I faced the same problem, but it appears to be resolved now.
> 
> ![image](https://user-images.githubusercontent.com/85361211/285258812-266e6e1e-69b3-4fc8-b6ab-ceaab66e3166.png)

Yes! It is working now. Thanks for the info!
