### ISSUE TITLE
404 Repository not found

### ISSUE THREAD

**Issue by Poisonlocket** [athul/waka-readme#154]
I ran my workflow with the following config:
![image](https://github.com/athul/waka-readme/assets/128643203/ab9d445f-f2ec-4e04-8d73-43119ed39c43)

this was the output:
![image](https://github.com/athul/waka-readme/assets/128643203/a430fe9d-4aa2-4fc7-864a-a34cc6aa50bd)

i did not specify any github Token as this is my personal readme

**Comment by Poisonlocket** [comment]
Okay so i did some research and i found out that the api call from the Waka readme repo and the actual api dont match. Basically the api call for my repo is api.github.com/repos/Poisonlocket/Poisonlocket. This program calls to api.github.com/poisonlocket/poisonlocket which is the reason why it cant find it

**Comment by Poisonlocket** [comment]
Might also be an Issue with it not finding the master Repository for some reason. Did some further testing

**Comment by yozachar** [comment]
[Here](https://github.com/Poisonlocket/Poisonlocket/blob/a1876d23ccae73e2b445aa10ee9ec245338f6b3f/.github/workflows/waka-readme.yml#L25-L27)

```yaml
          TARGET_BRANCH: main
          REPOSITORY: repos/Poisonlocket/Poisonlocket
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
```


You do not need to specify these three keys on profile readme. But if you do, `REPOSITORY` value is just `Poisonlocket/Poisonlocket`.

See: https://github.com/yozachar/yozachar/blob/master/.github/workflows/waka.yml

**Comment by Poisonlocket** [comment]
had to delete the file and make a new one, for some reason the workflow runner used an old version
