### ISSUE TITLE
Ignore "language names" with spaces in-between

### ISSUE THREAD

**Issue by Poisonlocket** [athul/waka-readme#155]
considering it has a space im not sure how to ignore it in the YAML format in the config.

**Comment by yozachar** [comment]
```yaml
 IGNORED_LANGUAGES: YAML "GitIgnore file" TOML
```

**Comment by Poisonlocket** [comment]
> ```yaml
>  IGNORED_LANGUAGES: YAML "GitIgnore file" TOML
> ```

Ive already tried that, doesnt seem to work, verified it with the config

**Comment by Poisonlocket** [comment]
![image](https://github.com/athul/waka-readme/assets/128643203/aee3af28-74dc-4e80-9cf1-b7e70e983d0e)
![image](https://github.com/athul/waka-readme/assets/128643203/7f2b3f57-2788-4439-a9fa-6d76f8636e85)

**Comment by yozachar** [comment]
https://github.com/athul/waka-readme/blob/a359b8d3e969e8b68018a187f10d1a22e45dffe5/main.py#L318

Right, this needs to be improved.

**Comment by Poisonlocket** [comment]
> https://github.com/athul/waka-readme/blob/a359b8d3e969e8b68018a187f10d1a22e45dffe5/main.py#L318
> 
> Right, this needs to be improved.

I'd be more than happy to fix this

**Comment by yozachar** [comment]
PR is welcome.

**Comment by Poisonlocket** [comment]
> PR is welcome.

Its probably not possible to keep it the way but if i update it with comma separation its possible

**Comment by yozachar** [comment]
Coma separation will work, but you might not want to upset, no idea how many of `~7k` users use the `IGNORED_LANGUAGES` already.

![image](https://github.com/athul/waka-readme/assets/38415384/fa3637e7-b0a5-4b48-9fa8-d91b715d1bd3)

**Comment by Poisonlocket** [comment]
> Coma separation will work, but you might not want to upset no idea how many of those `~7k` users use the `IGNORED_LANGUAGES` flag.
> 
> 
> 
> ![image](https://github.com/athul/waka-readme/assets/38415384/fa3637e7-b0a5-4b48-9fa8-d91b715d1bd3)
> 
> 

Makes sense, will probably just take all the languages received from Wakatime and if I find it in the Ignored langs string I'll strip it.
