### ISSUE TITLE
Ignored languages is broken on `master`

### ISSUE THREAD

**Issue by Vexcited** [athul/waka-readme#157]
Hey! First of all, thanks you for this action, I've been using it a lot for my profile README.

Even though, since [this commit](https://github.com/athul/waka-readme/commit/bc65b48ca263d7cc8052b06b028bd589c9a59f90), using `IGNORED_LANGUAGES: Other` in [my configuration](https://github.com/Vexcited/Vexcited/blob/main/.github/workflows/wakatime-cron.yml#L18) is broken.

- Day before the commit : https://github.com/Vexcited/Vexcited/commit/4816c07f61d1196c7640148bba8f1cb92158fa29
- Day after the commit : https://github.com/Vexcited/Vexcited/commit/9510fc0c12f55c4030d16bd859877dae3631c196

You can see that `Other` language comes back in the output.

Is there any update on what it should takes as input that is not documented yet ? 

Thanks you!

**Comment by yozachar** [comment]
Hey @Vexcited, sorry for the trouble, I've fixed it in #158.
