### ISSUE TITLE
Error with last build probably some issue with last commit.

### ISSUE THREAD

**Issue by riginoommen** [athul/waka-readme#18]
![image](https://user-images.githubusercontent.com/3840244/88166308-b0839300-cc34-11ea-927f-a6dadd3aeefb.png)

**Comment by athul** [comment]
Hey @riginoommen, I have a few speculations on why this is happening. I'm not sure which is the issue correctly but here you go
- that you might haven't saved the wakatime API key
- You have just started using wakatime and coding activity isn't updated till midnight.

> I jad just run the action on my repo and it seems to work just fine.

**Comment by Smartuil** [comment]
I have the same problem

**Comment by gautamkrishnar** [comment]
@athul If I am inferring correctly, The `lang_data` array is empty in this case. Can you try out the workflow after signing up as a new user without any stats?

**Comment by athul** [comment]
Yes, I just ran the code and it's due to the empty list, maybe a `if` condition will be enough to resolve the issue or a try except block? Try except could help us exit with a warning method

**Comment by gautamkrishnar** [comment]
@athul Don't exit with a status > 1, Just put a console log to let the users wait till the next day or their data is empty.

**Comment by athul** [comment]
So I guess I should remove all the `sys.exit(1)` from the code

**Comment by gautamkrishnar** [comment]
@athul yes do exit(1) only when you have some required parameters error or API fetching error. Users will receive a notification via email whenever a job fails.

**Comment by sebastiandg7** [comment]
+1. Happening here too, with recently created account. Have you tested what happend when a user does not log any time for a week? Maybe this land_data array is also empty, I think you should write something like "No time tracked this week 😅".

**Comment by athul** [comment]
Sorry for the bug. Sending a PR in a few mins

**Comment by athul** [comment]
Hey @riginoommen @Smartuil @sebastiandg7 could you check and verify if its working?

**Comment by riginoommen** [comment]
I verified it. Job is working fine in the logs but its not pulling the stats.i reverified the secrets also

![image](https://user-images.githubusercontent.com/3840244/88210038-2f96bc80-cc71-11ea-9fe2-bdcf77ca0327.png)

**Comment by athul** [comment]
BTW @riginoommen did you start using it today?

If yes. Wait till 00.00 UTC since thats the time the API data gets updated

**Comment by riginoommen** [comment]
I triggered this manually now still same results

**Comment by athul** [comment]
I meant, Did you start using wakatime today?

**Comment by riginoommen** [comment]
Yes

**Comment by athul** [comment]
Okay, then don't worry. It'll generate the updated stats tommorow morning(5.30 AM IST)

**Comment by Smartuil** [comment]
> Hey @riginoommen @Smartuil @sebastiandg7 could you check and verify if its working?

It's working.

**Comment by riginoommen** [comment]
Yay its working now

**Comment by athul** [comment]
Since it's solved, I guess its safe to close this issue. Feel free to open one if you found any ither bugs
