### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Smartuil** [athul/waka-readme#20]
What is this? It looks redundant
![image](https://user-images.githubusercontent.com/25101328/88246931-a3b37d80-ccce-11ea-90f9-aa213c2240a2.png)

**Comment by athul** [comment]
It looks fine on my screen. I can't seem to reproduce the above issue

**Comment by Smartuil** [comment]
I ues chrome, but I look yours,It looks like this:
> ![image](https://user-images.githubusercontent.com/25101328/88248347-77e6c680-ccd3-11ea-829d-d96170640c77.png)

It's too strange

**Comment by Smartuil** [comment]
I found this
> ![image](https://user-images.githubusercontent.com/25101328/88248591-520df180-ccd4-11ea-868a-d0e9239e9114.png)

When I pressed crtl and scrolled the mouse wheel to 200%,it looks well

**Comment by athul** [comment]
Seems like a rendering issue when zoomed out. Could you try on any other browser too just to confirm it's browser related

**Comment by Smartuil** [comment]
I test on QQ/Chrome/Edge browser,when it's 200%,it's OK,Other cases are not good

**Comment by athul** [comment]
I'm really sorry. I don't think there is anything we could do to resolve the issue with the code. 

Therefore closing it. Feel free to open an issue if you find any other bugs

**Comment by nelson6e65** [comment]
I'm having this issue too.

**Comment by athul** [comment]
This isn't an issue on the code side and mostly an issue with the browser and OS
