### ISSUE TITLE
How to hide some languages

### ISSUE THREAD

**Issue by chenboshuo** [athul/waka-readme#27]
I want to hide some items of WakaTime, but I don't know how to do it.

for instance,
I am using the WakaTime chrome to record my browse time,
but I don't want to show it in my readme.

```text
Other          13 hrs 17 mins  ███████████░░░░░░░░░░░░░░   46.76 % 
TeX            12 hrs 21 mins  ███████████░░░░░░░░░░░░░░   43.50 % 
Python         1 hr 38 mins    █░░░░░░░░░░░░░░░░░░░░░░░░   05.78 % 
OpenEdge ABL   25 mins         ░░░░░░░░░░░░░░░░░░░░░░░░░   01.51 % 
Markdown       21 mins         ░░░░░░░░░░░░░░░░░░░░░░░░░   01.26 %
```
I want to hide  item `Other` .
```text
TeX            12 hrs 21 mins  ███████████░░░░░░░░░░░░░░   43.50 % 
Python         1 hr 38 mins    █░░░░░░░░░░░░░░░░░░░░░░░░   05.78 % 
OpenEdge ABL   25 mins        ░░░░░░░░░░░░░░░░░░░░░░░░░   01.51 % 
Markdown       21 mins         ░░░░░░░░░░░░░░░░░░░░░░░░░   01.26 %
```

If you have related settings, could you think about this feature,
Thank you!

**Comment by athul** [comment]
This could be implemented with a new flag in our GitHub Action. But the downside is that it will affect the total percentage in the output like above in your stats, if we remove the "other" language the total % would be 52.05 and nearly the half the time is invisible to the public since it would be invisible to the public eye. 

If you really need this feature, it's simple since check the flag if it's either true or false and if it's false delete or omit that dict. @joe733 would you like to take this up or @chenboshuo would you?

**Comment by chenboshuo** [comment]
Yes, I think sometimes `other` is meanless because only the user know its means and we usually want to show the time of coding.

Thanking for your consideration。

**Comment by joe733** [comment]
How about this?

https://github.com/athul/waka-readme/blob/ec917b7b5dbb41ededce6b1602e4797e0c05ae62/main.py#L51-L54

**Comment by joe733** [comment]
Would it be good to put `Other` at the end of the top languages?

**Comment by athul** [comment]
That would be fine I guess, what do you say @chenboshuo ?

**Comment by joe733** [comment]
Okay here's what I could come up with... 

https://github.com/athul/waka-readme/blob/cc17cfda8be6ea198d0cdd9d4eba1a2178cb58f7/main.py#L51-L57

This probably hides the language tagged as `Other`, but I couldn't test it with my WakaTime data. @chenboshuo can you tell the results after testing it?

You can manually do that by cloning the [`rm-other`](https://github.com/athul/waka-readme/tree/rm-other) branch or change the following line in your workflow file:

from:
```
- uses: athul/waka-readme@master
```

to:
```
- uses: athul/waka-readme@rm-other
```

Don't forget to change it back later :wink:

**Comment by chenboshuo** [comment]
> That would be fine I guess, what do you say @chenboshuo ?

```text
Week: 29 July, 2020 - 05 August, 2020

TeX            4 hrs 58 mins   ██████░░░░░░░░░░░░░░░░░░░   24.96 % 
Python         3 hrs 34 mins   ████░░░░░░░░░░░░░░░░░░░░░   17.89 % 
OpenEdge ABL   23 mins         ░░░░░░░░░░░░░░░░░░░░░░░░░   01.95 % 
Markdown       17 mins         ░░░░░░░░░░░░░░░░░░░░░░░░░   01.43 % 
JSON           10 mins         ░░░░░░░░░░░░░░░░░░░░░░░░░   00.88 %
```

Yes it works,Thank you.
