### ISSUE TITLE
Redundant Pipfile

### ISSUE THREAD

**Issue by divykj** [athul/waka-readme#42]
The repository has both `requirements.txt` and `Pipfile`. The former is used in the docker build, which makes `Pipfile` redundant and unnecessary.

**Comment by joe733** [comment]
@divykj any side effects, if it's removed? For example will it hamper further development - say a complete refactoring of code to implement in `class` ?

**Comment by divykj** [comment]
So basically, `requirements.txt` and `Pipfile` (along with `Pipfile.lock`) do the same thing, that is dependency management.

> any side effects, if it's removed?

Since only `requirements.txt` is being used during the build, there's no side effect that I can see.

> For example will it hamper further development - say a complete refactoring of code to implement in `class` ?

It doesn't affect the working of python itself, it just changes how you store and retrieve your dependencies in python during development and during the build.

Also, I think it is completely unnecessary to implement a class-based approach.
Diving it into submodules could be a better approach.

**Comment by joe733** [comment]
> It doesn't affect the working of python itself, it just changes how you store and retrieve your dependencies in python during development and during the build.

I see. I'm not much familiar with these yet, I hope someone else with better experience can tell.

> Also, I think it is completely unnecessary to implement a class-based approach.

Why, are classes bad in some way?

> Diving it into submodules could be a better approach.

Yea that will be good.

**Comment by divykj** [comment]
> I see. I'm not much familiar with these yet, I hope someone else with better experience can tell.

I can assure you `Pipfile` is redundant *here*, and nothing will break.

> Why, are classes bad in some way?

No, they aren't bad, but they just don't have a use in this particular case.
Here we need more of a script, instead of a complex intertwined project with different objects interacting with each other, and for scripting, the object-oriented paradigm will not be that useful.

> Yea that will be good.

Yes, if you plan to implement more features, just tag me, I'll be ready to rewrite and divide it into scalable and sensible submodules.

**Comment by joe733** [comment]
> I can assure you `Pipfile` is redundant here, and nothing will break.

Alright then, I think we good to go.

> Here we need more of a script, instead of a complex intertwined project with different objects interacting with each other, so for scripting, the object-oriented paradigm will not be that useful.

That's right. Now I understand certain things... :)

> Yes, if you plan to implement more features, just tag me, I'll be ready to rewrite and divide it into scalable and sensible submodules.

It would be great. I'd love to help as much as I can.

**Comment by joe733** [comment]
Hi, wow, it's been over a year!

I've been messing around with Python and I've switch from `Conda` to `Pipenv` due to multiple reasons and so far it's been good. I think keeping the `Pipefile` is okay, even though it uses `requirements.txt` if the former is not found:

```txt
waka-readme on  master on 🐳 v20.10.8 
➜ pipenv shell    
Creating a virtualenv for this project...
Pipfile: /home/jovial/Documents/Workspace/VCServers/GitHub/joe733/0_forks/waka-readme/Pipfile
Using /usr/bin/python3 (3.9.7) to create virtualenv...
⠙ Creating virtual environment...created virtual environment CPython3.9.7.final.0-64 in 637ms
  creator CPython3Posix(dest=/home/jovial/.local/share/virtualenvs/waka-readme-l3_9yXYH, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jovial/.local/share/virtualenv)
    added seed packages: pip==21.2.4, setuptools==57.4.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/jovial/.local/share/virtualenvs/waka-readme-l3_9yXYH
requirements.txt found, instead of Pipfile! Converting...
✔ Success! 
Warning: Your Pipfile now contains pinned versions, if your requirements.txt did. 
We recommend updating your Pipfile to specify the "*" version, instead.
Launching subshell in virtual environment...
```

Closing this issue now, feel free to comment your thoughts below.

Happy coding ✌🏻
