### ISSUE TITLE
add anchor link

### ISSUE THREAD

**Issue by azizramdan** [athul/waka-readme#44]
Can you add anchor link to graph? so when graph clicked it will open https://wakatime.com/@username

**Comment by joe733** [comment]
Hi @azizramdan thank you for taking interest in the repository.

Is this something you're expecting?

<a href="https://wakatime.com/@joe733">
<pre>Week: 25 September, 2020 - 02 October, 2020
C        4 hrs 48 mins   ████████░░░░░░░░░░░░░░░░░   32.20 % 
Other    3 hrs 29 mins   ██████░░░░░░░░░░░░░░░░░░░   23.34 % 
Python   3 hrs 24 mins   █████▓░░░░░░░░░░░░░░░░░░░   22.79 % 
C++      1 hr 37 mins    ██▓░░░░░░░░░░░░░░░░░░░░░░   10.91 % 
Text     1 hr 18 mins    ██▒░░░░░░░░░░░░░░░░░░░░░░   08.78 % </pre></a>

**Comment by azizramdan** [comment]
@joe733 yes like that

**Comment by joe733** [comment]
Few things...

- This was done using HTML `<a href=''><pre></pre></a>` tags because multi-line markdown code <code>```</code> syntax does not support links.
- The user of WakaTime me need to have a `username`. Ironically I created one, just after I saw this issue.
- Alternative to this will be to have links on the _headline_ itself. Gives flexibility to the user and reduces code complexity.

I think the 3<sup>rd</sup> point is compelling, what do you think about having links in the headline?

### [:bar_chart: My weekly development breakdown](https://wakatime.com/@azizramdan)

**Comment by azizramdan** [comment]
1st point is worked but I don't like link's style, so I use 3rd point. Thanks
