### ISSUE TITLE
Skew appearance of progress bar Windows 10?

### ISSUE THREAD

**Issue by spencer741** [athul/waka-readme#56]
Not sure if this is happening to anyone else when viewing in either firefox or chrome browsers on Windows 10, there appears to be a weird skew happening.
![Capture](https://user-images.githubusercontent.com/35856129/108597727-32b17280-7350-11eb-9eaa-13107c2a1c2e.PNG)

@athul ... It appears this way for the graph in your profile as well.

I have restarted both browsers and my machine.. I know I just updated windows last night.

Edit: It is rendering correctly on firefox and chrome on Mac OSX, but not on either browser since the new Windows 10 update...

Can anybody confirm this behavior?

**Comment by spencer741** [comment]
I just realized this is an issue in issue #36 and #20 ... Does anybody have a clue as to what might be causing this behavior so we can resolve the bug upstream in the browsers or OS? Seems like a fair amount of people are/were having this issue.

**Comment by spencer741** [comment]
@smartuil Did you ever find a resolve to this?

**Comment by athul** [comment]
Hey @spencer741 This seems to be an issue only limited to Windows 10 devices. Possibly a rendering issue. One way you could tackle this issue would be to use another text/blocks like this

```yml
- uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
```

Ref: https://github.com/athul/waka-readme#extras

**Comment by spencer741** [comment]
Thanks for the insight. I just spent an hour or so testing how UniCode is rendered in GH markdown on Windows 10 vs Mac OSX. Some very interesting differences. It has to be how Windows 10 interprets unicode vs Mac, although pasting unicode chars into notepad and textedit don't seem to differ all that much... kind of confusing if you ask me.

I will go ahead and close this issue.

refs:
https://www.fileformat.info/info/unicode/char/2591/index.htm
https://www.unicode.org/charts/PDF/U2580.pdf

**Comment by Curtion** [comment]
I found that this problem occurs when using `pre`and `code` tag in github, Maybe can use the `table` tag to solve this problem。
Here's a way to display it correctly, although it changes the style

![old](https://user-images.githubusercontent.com/14846890/159616883-652e194c-08f4-4fdb-94e0-59f71561caae.png)
![new](https://user-images.githubusercontent.com/14846890/159616890-ff09a018-b7b7-48e8-899d-5905a0825d74.png)

But, Can't contribute healthy code as I don't use python. 

Code I tested:  https://github.com/Curtion/waka-readme/blob/master/main.py

**Comment by joe733** [comment]
[![image](https://user-images.githubusercontent.com/38415384/159926977-f77447c5-087f-40b8-aabc-1c43f2207217.png)](https://github.com/eli1stark)

Apparently this happens on Firefox on Arch Linux too. Hence https://github.com/athul/waka-readme/issues/20#issuecomment-683664322 is apt.

**Comment by joe733** [comment]
> I found that this problem occurs when using `pre`and `code` tag in github, Maybe can use the `table` tag to solve this problem。 Here's a way to display it correctly, although it changes the style
> 
> ...
>
> But, Can't contribute healthy code as I don't use python.
> 
> Code I tested: https://github.com/Curtion/waka-readme/blob/master/main.py

I'm afraid `<table>` won't help either... 

Firefox
![image](https://user-images.githubusercontent.com/38415384/159928001-4191b454-6575-4a61-b73e-024fb597178c.png)

Brave
![image](https://user-images.githubusercontent.com/38415384/159928203-7216a71d-7134-4ad0-bac9-780bcff8770b.png)
