### ISSUE TITLE
Filter out languages based on coding time

### ISSUE THREAD

**Issue by blchelle** [athul/waka-readme#57]
One thing I wish I could do is to specify an option that filters out any languages that I've used for less than x amount of time in the last week. For example, I'm currently using this tool and my weekly stats look like this
```text
Week: 22 February, 2021 - 01 March, 2021

Rust         11 hrs 13 mins  ████████████▓░░░░░░░░░░░░   50.53 % 
Go           5 hrs 46 mins   ██████▓░░░░░░░░░░░░░░░░░░   26.02 % 
TypeScript   4 hrs 15 mins   ████▓░░░░░░░░░░░░░░░░░░░░   19.15 % 
Git Config   10 mins         ▒░░░░░░░░░░░░░░░░░░░░░░░░   00.76 % 
Text         9 mins          ▒░░░░░░░░░░░░░░░░░░░░░░░░   00.73 % 
```
The first three lines are very good at letting people know what I'm currently building with. The last two lines don't provide any useful information though and it would be really cool if I could filter these out by specifying an option in the github action like 
```yaml
with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          FILTER_TIME: 30 # 30 Minutes
```

I'm not sure if this is something that can even be implemented on your end as you're probably somewhat restricted by the Wakatime API.

**Comment by joe733** [comment]
Hey @blchelle thanks for bringing this up. I'm not sure if it'd be fully implemented soon, in the mean time please have a look at a very similar issue: https://github.com/athul/waka-readme/issues/27

**Comment by blchelle** [comment]
Thanks @joe733. It's certainly more of a "nice to have" than it is a "must have" feature

**Comment by joe733** [comment]
Hi @blchelle, are you still interested in this feature? I'm closing this for now. If anyone is, please bump this thread. PRs are welcome too!
