### ISSUE TITLE
Header issue (inaccurate week stats)

### ISSUE THREAD

**Issue by rajitbanerjee** [athul/waka-readme#7]
@athul Is there a way to change the header? It's actually not accurate. The Waka Time API returns metrics from the last 7 days from the current date, and not according to weeks of the year. @joe733 could you please modify the code so that the header displays the last 7 days: e.g. running the workflow on July 17 should return the header "Week: July 9 - July 16". I'm not sure what to do about the week number. 
![image](https://user-images.githubusercontent.com/44174210/87824088-89ac1200-c86c-11ea-9c7a-47c297d82658.png)

_Originally posted by @rajitbanerjee in https://github.com/athul/waka-readme/pull/6#issuecomment-660300180_

**Comment by joe733** [comment]
> The Waka Time API returns metrics from the last 7 days from the current date.

Oh I see.

> I'm not sure what to do about the week number.

I think it would be good to just drop it.

**Comment by athul** [comment]
Hey @rajitbanerjee if You feel the issue was solved, feel free to close the Issue. 😄

Thanks for reporting this bug and thanks @joe733 for fixing it
