### ISSUE TITLE
Update Screenshots and path

### ISSUE THREAD

**Issue by samr1ddh1** [athul/waka-readme#71]
I wanted to integrate this into my markdown file, however I stumbled upon this issue.
For the Profile Repository Section ,step No. 3 and  its respective screenshots  need updation as that path no longer exists.
New path will be `https://github.com/USERNAME/USERNAME/settings/secrets/actions/new`

<img width="427" alt="image" src="https://user-images.githubusercontent.com/52720626/151221742-bc37d139-2bb3-4554-b27c-46b107d1f408.png">

**Comment by joe733** [comment]
Hi @samr1ddh1, thanks for the heads up! PRs are welcome!
