### ISSUE TITLE
How long does it take for metrics to show up?

### ISSUE THREAD

**Issue by ibrahiem96** [athul/waka-readme#73]
Hi, 

I'm new to both Waka and Athul's waka-readme project. I just installed this action in my profile repo and its working great, but I don't see any of my metrics in my README as of yet. Is it because I have only been recording metrics for the past day? Can anyone shed light on this? 

Thanks

**Comment by joe733** [comment]
24 hrs usually, see https://github.com/athul/waka-readme/issues/53#issuecomment-767281814

**Comment by ibrahiem96** [comment]
@joe733 thanks, I see the metrics after a few days.
