### ISSUE TITLE
Change CI from Travis to GitHub Actions

### ISSUE THREAD

**Issue by athul** [athul/waka-readme#77]
I think it should be more apt to change the CI system to GitHub Actions itself than Travis. The current project itself is a GH action and it's ironic that we use Travis for Testing 🤣 .

Since Travis only does is installing python and it's requirements and running unittest, it should be fairly easy to port to GH actions. Refer `travis.yml` for details

**Comment by joe733** [comment]
Hi, yea it is kind of ironic, but say for instance if [GH Actions](https://www.githubstatus.com/) went down or [Travis](https://www.traviscistatus.com/) did, we could tell them apart when someone reports their workflow is failing. Just a thought.. :)

**Comment by athul** [comment]
Oh wait, I'm sorry for confusing this. I meant the tests for waka-readme repo. Those are done with Travis and we need to change that to GH actions

**Comment by joe733** [comment]
Yes, I understand.

The possibility of both the CI providers going down together is less than one going down, right.. so we can be sure that our latest commit (passes test in Travis CI and) did not cause some issue - in the scenario where GH Actions goes down (which would disrupt the WakaTime workflow for users).

But hey, I'm totally okay with having GH actions for testing, if that's what you want.
