### ISSUE TITLE
Proposal : Header/ Heading with the Action

### ISSUE THREAD

**Issue by athul** [athul/waka-readme#9]
Hey, I was hoping to add a Header for the metrics in the Readme section. Let's use GitHub Actions for the optional header part. 
The way we'll use it is with the `actions.yml` file. We can add a new `inputs` called `Header` and default to "" . If the user want to add a Header, he could add one. This in case will not break any of the current users stats and won't cause any issues(I hope it doesn't). The way we can add it is just add a new section in the input like this
```yml
  HEADER:
    description: 'The Header for your Stats'
    default: ""
```
And we can use this in python to generate a header with the stats itself.

What are your thoughts? Should this be added to the action or kept away from it. Every feedback is welcome

**Comment by joe733** [comment]
Which header are we talking about?

This one?
![Screenshot from 2020-07-18 12-37-06](https://user-images.githubusercontent.com/38415384/87847174-83ad4400-c8f3-11ea-9e0f-1114f9a6cc49.png)

or this one?
![Screenshot from 2020-07-18 12-38-00](https://user-images.githubusercontent.com/38415384/87847181-9162c980-c8f3-11ea-93e0-d39057dd2607.png)

**Comment by athul** [comment]
The former

**Comment by joe733** [comment]
[This](https://raw.githubusercontent.com/joe733/joe733/master/README.md) is the crooked :wink: way I'm using the header. I guess we'd have to do one more regex matching to locate it within readme.

**Comment by athul** [comment]
This would be an exception I'd say. But hey if we are going to implement the Header should be optional

**Comment by joe733** [comment]
> the Header should be optional

Yep, okay so the header is also passed in an an environment variable, right? and then...

```python
19. ghtoken = os.getenv('INPUT_GH_TOKEN')
20. header = os.getenv('HEADER') + '\n' if os.getenv('HEADER') != '' else os.getenv('HEADER')
# Because otherwise the newline will be still there even when the header is ''.

# ...... On the (then) 49th line

49. return header+```text\n'+this_week()+'\n\n'+data+'\n```'
```

this may work.

**Comment by divykj** [comment]
@joe733 maybe this?
```python
header = os.getenv('HEADER')
if header:
    header += '\n'
```

@athul should I put a PR?

**Comment by joe733** [comment]
> @joe733 maybe this?
> 
> ```python
> header = os.getenv('HEADER')
> if header:
>     header += '\n'
> ```
> 
> @athul should I put a PR?

yea.. give it a shot.

**Comment by divykj** [comment]
When you think about it, it seems completely unnecessary.
The header is static, so it doesn't need to be written by the action.
Also, different people like to put different types of headers.
```
📊 **Weekly development breakdown**
### 📊 Weekly development breakdown
```

The user will have to write markdown syntax in `actions.yml` which seems even more off.

I could still write a PR if you want!

@joe733 @athul

**Comment by joe733** [comment]
You're right the, header does not change per say. And it may vary in taste from person to person. What are your thoughts @athul?

**Comment by athul** [comment]
Hey, @joe733 @divykj Thanks for the discussions, but this of low priority since no one else has requested it. Thanks again for the fine discussion here.


Closing this ☺️
