### ISSUE TITLE
API Returning 202 - ACCEPTED

### ISSUE THREAD

**Issue by mariarobertap** [athul/waka-readme#95]
Hello. Just started using this action, and I'm having a problem. 
The jobs keep failing. Notice that a couple of people are having the same issue.
Is there any solution?

`[2022-08-22 20:40:06] ln. 309 DEBUG    API response @ trial #1: 202 • ACCEPTED`

Thanks!

**Comment by nishant-nayak** [comment]
Hi @mariarobertap , any idea how it started working again? I'm facing the same issue with my workflow and I'm not sure what's causing the issue.

**Comment by reekystive** [comment]
@nishant-nayak You can refer to this issue: https://github.com/athul/waka-readme/issues/98
