### ISSUE TITLE
Waka readme not updating automatically. Manual running also not working

### ISSUE THREAD

**Issue by chitraarasu** [athul/waka-readme#97]
![Screenshot 2022-09-07 080140](https://user-images.githubusercontent.com/75994428/188776314-bec92a41-feb3-4811-9ce3-ee289ebe49c4.png)
![Screenshot 2022-09-07 080921](https://user-images.githubusercontent.com/75994428/188776404-46380288-69b9-4df1-86af-6fb1f89cab75.png)

**Comment by joe733** [comment]
Hi @chitraarasu, the error message plainly says you're providing "Bad credentials", please check if your GitHub token has proper scope and has not expired.

By the way, looks like you're using this action on your on [profile readme](https://github.com/chitraarasu/chitraarasu/blob/master/.github/workflows/waka-coding-stats-workflow.yml). You do not have to provide GitHub token. [RTM](https://github.com/athul/waka-readme).

![image](https://user-images.githubusercontent.com/38415384/188784723-e55d48b5-262f-4a3f-a9cb-56de7fe3f23c.png)


![image](https://user-images.githubusercontent.com/38415384/188784670-0faa7b57-12a6-4628-abaf-2494a1c6cecf.png)

**Comment by chitraarasu** [comment]
Thank you
